## Was machen wir? {#fachschaft-was-machen-wir}

### Erstsemesterbetreuung {-}

Wie im Erstibrief zu lesen ist, gibt es dieses Jahr wieder einige Veranstaltungen für euch. Darunter fallen die Kneipentour, Stadtrallye und das Erstiwochenende auf Wallenfels. Für die Kneipentour sind zwei Termine vorgesehen (08.10. und 16.10.26). Die Stadtrallye findet am Samstag, dem 10.10., also direkt vor Vorlesungsbeginn, statt. Das Erstiwochenende findet Anfang November statt. Die Anmeldung zum Erstiwochenende folgt noch.<br>
Ab dem 12.10. könnt ihr eure Erstitüten in der Fachschaft abholen, die tolle Dinge beinhaltet!

### Studibetreuung {-}

Neben unserem Wohlfühlprogramm zum Eingewöhnen in das Studium für unsere Erstis bieten wir allen Studierenden das ganze Jahr über Hilfe an. Keine Frage bleibt bei uns unbeantwortet und kein Problem ungelöst. Zum einen versorgen wir euch mit dem Rüstzeug aller guten Naturwissenschaftler\*innen (**Kittel `r knitr::knit_child("data/preise-kittel.txt")`€**, **Sezierbesteck `r knitr::knit_child("data/preise-sezierbesteck.txt")`€**), welches bei uns zum Selbstkostenpreis erworben werden kann. Das Sezierbesteck könnt ihr ab diesem Jahr auch bei uns ausleihen, was wir euch persönlich eher empfehlen als es zu kaufen - in der Regel braucht ihr es nur im ersten Semester eures Studiums. Zum anderen bieten wir auch Altklausur-Exemplare für viele Fächer an, sodass ihr euch optimal auf Prüfungen vorbereiten könnt. Die Altklausuren liegen digitalisiert vor und sind kostenfrei. Die  **Altklausuren** fragt ihr bitte per E-Mail an oder ihr kommt persönlich mit einem USB-Stick bei uns vorbei. Eure Anfrage wird so schnell wie möglich bearbeitet. All das funktioniert natürlich nur, wenn ihr eure geschriebenen Klausuren für die nachfolgenden Jahrgänge auch wieder vorbeibringt. 

### Fachschaftsdienst {-}

Die obig genannten Service-Leistungen können ganzjährig während der Vorlesungszeit von 12.00 - 14.00 Uhr in Anspruch genommen werden. Außerhalb der Öffnungszeiten gilt: einfach klopfen, wenn ihr Glück habt, ist jemand da, der euch weiterhilft. 🙃

### Uni gestalten {-}

Wir gestalten aktiv eure Studiengänge sowie Lehr- und Lernumgebungen, indem wir eure Interessen in diversen Gremien der Uni vertreten. In der Studienzuschusskommission entscheiden wir zusammen mit den Professor\*innen, für welche Fächer zusätzliche Übungen und Tutorien finanziert werden, damit ihr besser auf die Prüfungen vorbereitet seid. Im Prüfungsausschuss vertreten wir eure Interessen, wenn es um Änderungen der Prüfungsordnung geht, und in der Fachgruppe bringen wir eure Anregungen und Vorschläge mit ein, um Probleme in einem Studiengang zu beseitigen und dessen Studierbarkeit zu verbessern.

Auch im obersten Gremium der Fakultät, dem **Fakultätsrat**, sowie auf der Ebene der gesamten Universität, im [**Studierendenparlament**](#stupa), sind wir mit von der Partie und vertreten eure Interessen. Daher wendet euch bei Problemen und Anregungen an uns, sodass wir diese beheben können.

Die gerade zu Beginn für euch interessantesten Themen spielen sich allerdings in unseren Fachschaftssitzungen ab. Diese finden wöchentlich statt, sind öffentlich und ihr seid herzlich eingeladen. Über den Wochentag und die Uhrzeit wird zu Beginn des Semesters abgestimmt und das dann bekannt gegeben.

### Veranstaltungen {-}

Was Veranstaltungen betrifft, gibt es vieles auf das ihr euch freuen dürft. Das nächste, auf das ihr stoßen werdet, sind die zwei Kneipentouren, ein Spieleabend mit allen Fakultäten, ein Pubquiz und das Ersti-Wochenende in Wallenfels.

Außerdem erwartet euch um Nikolaus unsere legendäre Nikofete, wobei der Nikolaus immer fleißige Helferlein braucht.🎅 Dabei verwandelt sich das ganze NW I in eine große Party-Area, mit einer Band plus DJ. Natürlich ist dabei auch für dein leibliches Wohl gesorgt.

Darüber hinaus verleihen wir auch am Anfang jedes Jahres die Goldene Kreide, mit der ein\*e Dozent\*in für herausragende Lehre ausgezeichnet wird. Nach einer kurzen Ansprache und einem Vortrag der honorierten Lehrperson lassen wir die Feierlichkeiten bei Bier und Brezeln ausklingen. Um Kriterien für die Vergabe zu haben, führen wir am Ende jedes Semester eine Evaluation aller Vorlesungen einer Fachgruppe durch.

### Wie kannst du dich einbringen und wo sind wir zu finden {-}

Wenn du jetzt auch Interesse hast, auf einem unserer zahlreichen Themengebiete mitzuwirken, schau doch einfach mal während des Fachschaftsdienstes vorbei oder komm auf eine unserer Sitzungen: Wir freuen uns über jedes neue Mitglied!

Und keine Sorge, du musst nicht das volle Programm mitmachen, sondern kannst klein einsteigen, zum Beispiel, indem du uns einfach mal deine Meinung sagst. Also komm einfach vorbei!☺️

Zu finden sind wir im Gang des NW I, ganz in der Nähe der Hörsäle H13, H14 und H15. Dort hängt auch unser Fachschaftsbrett, an dem du immer die aktuellen Neuigkeiten zu unserer Arbeit und zu Veranstaltungen an der Uni findest. Du kannst uns natürlich auch auf elektronischem Wege kontaktieren:

Telefon: 0921 / 55 - 2212<br>
Email: fs-bcg@uni-bayreuth.de<br>
Website: https://www.fsbcg.uni-bayreuth.de

💚Viel Spaß während deines Studiums und einen erfolgreichen Abschluss, deine Fachschaft BCG 💚