## Bachelor Geoökologie

Hallo liebe Gecko-Erstis!<br>
Herzlich Willkommen an der Uni!

Wie ihr bestimmt schon gehört habt, ist Geoökologie eine interdisziplinäre, also fächerübergreifende Naturwissenschaft. Das merkt man vor allem in den ersten beiden Semestern,
in denen die Grundlagen behandelt werden: Ob Mathematik, Physik oder Chemie - es ist immer wichtig, gut mitzulernen, damit man später in anderen Fächern schneller durchsteigen kann.
Für alle, die in Mathematik etwas unsicher sind, wird in den Wochen vor Vorlesungsbeginn ein Vorkurs angeboten.
Leider nützt euch diese Information nun nichts mehr. Ha! Aber lasst euch nicht abschrecken, in jedem Semester werden die Fächer interessanter.
Auch für die Geoökologie selbst wird im ersten Semester die gleichnamige Vorlesung angeboten, um euch gleich zu Beginn einen Eindruck über die geoökologischen Grundlagen zu vermitteln.

### 1. Semester {-}

#### Mathematik 1, Physik 1, Anorganische und Analytische Chemie {-}

In Physik und Mathematik gilt: nicht verzagen, wenn man die Theorie mal nicht ganz kapiert hat. Wichtig ist es, immer in die Übungen zu gehen und dort alles anwenden zu können.

#### Allgemeine Ökologie und Modellbildung in der Geoökologie {-}

Ökologie ist eine sehr interessante Vorlesung, die zum Nachdenken motiviert. Einen guten Einstieg in den Studiengang Geoökologie ermöglichen diese beiden Vorlesungen, da sie gut an den Schulstoff anknüpfen.

#### Litosphäre 1 — Geologie {-}

Diese Vorlesung deckt die Einführung in die Geologie aber auch in die Mineralogie ab.

### 2. Semester {-}

#### Physikalische Chemie und Organische Chemie {-}

Unbedingt alle Übungen besuchen. In Organischer Chemie (OC) und Physikalischer Chemie (PC) ist grundlegendes Verständnis sehr wichtig.
Generell empfiehlt es sich für Chemie, früh mit dem Lernen zu beginnen, da der Stoff sehr umfangreich ist.

#### Geomorphologie {-}

Juhu – es geht mit dem Lithosphären Modul weiter, und jetzt sogar mit Exkursion!

#### Hydrologie {-}

Das zweite Geoökologische Grundlagenmodul beginnt - Wasser! Hier könnt ihr euch auch auf eine Exkursion freuen!
Geht in die Übungen und lasst euch den Vorlesungsstoff noch einmal kurz zusammenfassend erklären, das hilft sehr für die Klausur!

#### Einführung in die Bodenkunde {-}

Uuuunnd das 3. Wichtige Modul für euch! Beginnend mit Bodenkunde werdet ihr in die Thematik des Bodens eingeführt.

#### Biosphäre

Im Biosphären Modul geht’s um Pflanzen! In Pflanzenbestimmung habt ihr viele interessante Exkursionen, lernt mit Bestimmungsbüchern umzugehen und könnte hoffentlich am Ende des Kurses ein paar Pflanzen erkennen.
Tipp: Leiht euch am besten frühzeitig ein Buch aus der Bib aus!

#### Wissenschaftliches Lesen und Abstract schreiben

In dieser Vorlesung kommt ihr zum ersten Mal Kontakt mit Wissenschaftlichen Texten! Es soll euch helfen damit umzugehen und daraus gute Zusammenfassungen zu gewinnen.
All diese Infos nur noch detaillierter findet ihr im Modulhandbuch. Der Studienplan für Geoökologen gibt euch nur einen Überblick über alle Module.
Mehr Informationen zu den Vorlesungen und allem anderen unter https://www.bscgeooekologie.uni-bayreuth.de/de/studierende/index.html.

Achtung! Achtet drauf nur in der Prüfungsordnung/Modulhandbuch nachzuschauen, das für euch ist! Ihr seid der erste Jahrgang mit dieser neuen Ordnung!
Lasst euch auch von höheren Semestern nicht verwirren, sie haben einen anderen Studienplan als ihr – Aber fragt trotzdem nach - egal ob in der Fachschaft oder bei euren Tutoren,
wir haben immer ein offenes Ohr für euch!

**Viel Spaß beim Studienstart!**