## Bachelor Polymer- und Kolloidchemie

Polymer– und Kolloidchemie (PolKol) ist eine besondere Spezialisierung des Chemie-Bachelorstudiums, das deutschlandweit einzigartig ist.

Die ersten vier Semester sind dabei identisch mit dem „normalen“ Chemie-Studium, sodass ihr euch genau wie die Chemiker durch den Dschungel kämpfen müsst.
Häufig wird in den ersten vier Semestern auch gar nicht zwischen den beiden Studiengängen unterschieden, und bis zum Ende des vierten Semesters könnt ihr ohne Schwierigkeiten wechseln.

Im letzten Studienjahr beginnen dann die Unterschiede: Während Chemiker sich genauer mit organischen Synthesen (OC IV-Vorlesungen und Praktikum) und dem Aufbau von Stoffen (AC V-Vorlesungen und -Seminar) befassen,
interessieren sich PolKols für die Kolloidchemie und die Polymertechnologie. Bei beiden Veranstaltungen gibt es ein Praktikum.
Man könnte daher sagen, dass Chemiker sich mehr mit der AC und OC beschäftigen, während PolKols mehr PC und MC machen. Aber die Grenzen sind sehr fließend ...