## Unipolitik

Im Laufe eures Studiums werdet ihr mehr oder weniger Einblick in die Politik erhalten, die weit reichende Entscheidungen für euer Studium fällen wird.
Egal ob ihr euch dafür interessiert oder nicht, ihr werdet immer mittel- oder unmittelbar betroffen sein. Deswegen soll hier kurz das politische System an unserer Uni vorgestellt werden.
Ihr werdet sehen, dass ihr viele Möglichkeiten habt, aktiv eure Uni mitzugestalten.

Im Prinzip gibt es drei Gremien, die in die Entscheidungsprozesse der Universität involviert sind.

### Senat {-}

Das höchste und wichtigste Hochschulgremium ist der Senat. Er ist fakultätsübergreifend, d.h. für die ganze Uni zuständig. ln ihm werdet ihr von drei stimmberechtigten Studenten vertreten.
Dieses Gremium müssen praktisch alle Entscheidungen passieren, bevor sie in Kraft treten oder nach München zum Kultusministerium gesandt werden.
Beispiele sind die Studienordnungen oder die Einstellung eines Professors (Kandidatenliste der Berufungskommission, wenn ein Lehrstuhl neu besetzt werden muss).
Auch die Neugründung eines Lehrstuhls muss im Senat beschlossen werden. Kurz gesagt: Hier werden die Weichen für die Uni gestellt.
Viele der behandelten Themen sind umfangreich und komplex - deshalb sollten die Entscheidungen schon in anderen Gremien vorbereitet werden.

### Hochschulrat {-}

Ein weiteres Organ der Hochschulpolitik stellt der Hochschulrat dar. Er besteht nicht nur aus Angehörigen der Universität, sondern ist zur Hälfte mit externen Mitgliedern besetzt.
Er entscheidet über die strukturelle und strategische Ausrichtung der Hochschule sowie alle Satzungen.

### Studierendenparlament {-}

Die Meinungsfindung für uns Studenten findet im Studierendenparlament (StuPa) statt. Hier werden die drängenden Fragestellungen der Studenten diskutiert und dann im Senat gegenüber der Professorenschaft vertreten.

> Zitat aus der Rohfassung (zum Thema StuPa):<br>
> *Hier werden Deine Interessen und Bedürfnisse erarbeitet [...]*

Zusätzlich stehen dem StuPa eigene Geldmittel zur Verfügung. Diese werden teilweise den Fachschaften zur Verfügung gestellt und teilweise direkt eingesetzt.
Weitere Details findet ihr im folgenden, ausführlichen Text.

Im Fakultätsrat werden die fakultätsspezifischen Entscheidungen für den Senat vorbereitet. Der Fachschaftsvorsitzende sowie dessen Vertreter nehmen stimmberechtigt an den Sitzungen teil.
Hier werden Fragen zu Berufungskommissionen, Studienordnungen etc. - bezogen auf eine Fakultät - beraten. In deinem Fall sind das also die Entscheidungen für Fakultät II.
Da sich deine Fakultät aus drei teilweise sehr unterschiedlichen Fachgebieten zusammensetzt (Bio/Chemie/Geo), gibt es noch drei sog. Fachgruppen, in denen wir stimmberechtigt teilnehmen.
Die Fachgruppen geben Ratschläge an den Fakultätsrat, die in der Regel befolgt werden.

Natürlich braucht jeder, der studentische Interessen vertritt, den Rückhalt aus den eigenen Reihen. Deshalb ist eine hohe Wahlbeteiligung extrem wichtig.
Jede zusätzliche Stimme stärkt unsere Position. Denn jedes Jahr im Sommersemester werden die einzelnen Gremien gewählt.

**Also: wählen gehen! Damit wir uns auch weiterhin für euch an allen Fronten einsetzen können.**