## Wer ist eigentlich dieses StuPa

Herzlich willkommen an der Universität Bayreuth auch von uns! Das Studierendenparlament (kurz StuPa) ist eure fakultätsübergreifende Vertretung an der Uni und setzt sich,
z.B. vor der Verwaltung für die Belange der Studierenden ein.

### Wie sind wir aufgebaut? {-}

Das StuPa setzt sich zusammen aus zwölf Fachschaftsvertretern (je zwei pro Fachschaft), zwölf Mitgliedern aus Hochschulgruppen, zwei Mitgliedern aus dem Hochschulrat und drei Mitgliedern aus dem Senat.

Eure Vertreter_Innen wählt ihr jeden Juni für das kommende Hochschuljahr. Das StuPa wählt dann eine/n Vorsitzende/n und eine/n Stellvertreter/in sowie sechs Sprecherräte,
die sich um bestimmte Themenbereiche besonders kümmern und eure zentralen Ansprechpartner sind.

### Was tun wir so? {-}

Im letzten Jahr hat das Stupa unter anderem wieder erfolgreich die Verhandlungen zum Semesterticket bestritten und aktiv unsere Arbeitskreise,
wie zum Beispiel den AK Queer oder den neuen AK Uneingeschränkt Studieren, unterstützt. Über den AK Kultur und Kommunikation organisieren wir das Uniopenair, welches ihr auf keinen Fall verpassen solltet.

Ein sehr zentrales Thema ist die Verbesserung der Lehre. Wir arbeiten an einem besseren Evaluationskonzept und versuchen die „Digitale Revolution“ auch in die Hörsäle zu bekommen.

So könnt ihr zurzeit kostenlos das Angebot von video2brain nutzen. Weiterhin haben wir dieses Jahr das International Office evaluiert, um dort das Angebot laufend zu verbessern.
Ein großer Schritt in diesem Jahr war die Einführung des cmlife-Systems, welches wir weiter optimieren.

Nicht nur im Bereich der Lehre sind wir aktiv, auch kulturell wollen wir das Leben am Campus bereichern.
Die Campus-Kultur-Woche bietet stets ein breites Angebot und letztes Jahr wurden die "Bayreuther Debatten" mit spannenden Gästen und Diskussionen wieder ins Leben gerufen.

Weitere Themen sind stets die Verbesserung der Mensa und seit letztem Jahr gibt es ein Buddyprogramm, um Geflüchtete schnell zu integrieren.

Ihr möchtet wissen, was wir sonst noch alles treiben oder habt Fragen zur Universität? Dann schreibt uns an stupa@uni-bayreuth.de,
kommt zu einer unserer öffentlichen Sitzungen jeden zweiten Dienstag ab 20 Uhr, oder bringt euch gleich aktiv in einem der Ressorts oder Arbeitskreise ein!

Wir freuen uns über jede Anregung und wünschen euch ein spannendes erstes Semester an der Universität Bayreuth!