## Links {#links}

### Uni-Dienste {-}

**cmlife**<br>
Studienverwaltung, Kurs– und Prüfungsanmeldung<br>
https://my.uni-bayreuth.de/cmlife

**eLearning**<br>
Bereitstellung von Vorlesungsunterlagen<br>
https://elearning.uni-bayreuth.de

**Vorlesungsverzeichnis**<br>
-> siehe cmlife

**Prüfungsordnungen**<br>
Präzise Regelungen über euren Studiengang<br>
[Google: "uni bayreuth prüfungsordnungen"](https://www.google.com/search?q=uni+bayreuth+pr%C3%BCfungsordnungen)

**Termine**<br>
https://www.studierendenkanzlei.uni-bayreuth.de/de/termine

**Universitäre Mailadresse**<br>
Zugang/Verwaltung eurer Unimail-Adresse<br>
https://mail.myubt.de

### Einrichtungen {-}

**Fakultät II**<br>
https://www.bcg.uni-bayreuth.de

**Fachschaft**<br>
https://www.fsbcg.uni-bayreuth.de

**Bibliothek**<br>
https://www.ub.uni-bayreuth.de

**Mensa**<br>
[Hauptmensa](https://www.studentenwerk-oberfranken.de/essen/speiseplaene/bayreuth/hauptmensa.html)<br>
[Frischraum](https://www.studentenwerk-oberfranken.de/essen/speiseplaene/bayreuth/frischraum.html)

**Studentenwerk**<br>
https://www.studentenwerk-oberfranken.de

### IT {-}

**Laptopsprechstunde**<br>
Online, per E-Mail oder persönlich<br>
https://laps.uni-bayreuth.de

**PC Garage**<br>
Hilfe bei Hard- und Software-Problemen<br>
https://www.its.uni-bayreuth.de/de/hilfe-und-support

**Microsoft Office (Office 365)**<br>
Kostenlos für Studenten<br>
https://www.its.uni-bayreuth.de/de/hard-und-software

**eduroam/Netzzugang**<br>
Anmeldung für Uni-WLAN<br>
https://www.its.uni-bayreuth.de/de/internet-und-email

### Uni-Umfeld/Freizeit {-}

**Gültigkeit Semesterticket**<br>
https://www.studentenwerk-oberfranken.de/das-swo/semesterticket/informationen-bayreuth

**Hochschulsport**<br>
https://www.hochschulsport.uni-bayreuth.de

**UniTanzen**<br>
http://unitanzen.de

**Weitere Informationen findet ihr zudem auf den diversen Lehrstuhlseiten!**