## Ansprechpartner

### Zentrale Studienberatung {-}

Raum: 1.88 bis 1.92 (ZUV)<br>
Tel.: 0921 / 55 - 4433<br>
E-Mail: [studienberatung@uni-bayreuth.de](mailto:studienberatung@uni-bayreuth.de)<br>
Web: https://www.studienberatung.uni-bayreuth.de<br>
Telefon: Di. und Do. 10.00 - 11.00 Uhr<br>
Offene Sprechstunde via Zoom: Mi. 14.00 - 15.00 Uhr (mehr Informationen auf der Website)

Die Studienberatung bietet außerdem ein [Kontaktformular](https://www.studienberatung.uni-bayreuth.de/de/kontaktformular/index.php) an über das ihr euer Anliegen direkt eingrenzen könnt.

### Studierendenkanzlei {-}

Raum: 1.09 (ZUV)<br>
Tel.: 0921 / 55 - 5256<br>
E-Mail: [studierendenkanzlei@uni-bayreuth.de](mailto:studierendenkanzlei@uni-bayreuth.de)<br>
Web: https://www.studierendenkanzlei.uni-bayreuth.de<br>
Persönlich: Di., Mi., Do. von 09.00 bis 11.00. Mi. 13.30 bis 15.00.

### International Office {-}

Raum: 1.84 (ZUV, Vorzimmer)<br>
Tel.: 0921 / 55 - 5275 (Vorzimmer, Fr. Hoffmann)<br>
E-Mail: [international@uni-bayreuth.de](mailto:international@uni-bayreuth.de)<br>
Web: https://www.international-office.uni-bayreuth.de

### Sprachenzentrum {-}

Raum: GW I, Zi. 0.04<br>
E-Mail: [sprachenzentrum@uni-bayreuth.de](mailto:sprachenzentrum@uni-bayreuth.de)<br>
Web: https://www.sz.uni-bayreuth.de

### Prüfungsamt BCG {-}

Die Prüfungsämter an der Universität sind auf die einzelnen Fakultäten aufgeteilt. Für uns ist natürlich das Prüfungsamt BCG zuständig.

Raum: 1.34 (ZUV)<br>
Tel.: 0921 / 55 - 5253, - 5252 oder - 5267<br>
E-Mail: [pruefungsamt.zuv1@uni-bayreuth.de](mailto:pruefungsamt.zuv1@uni-bayreuth.de)<br>
Web: https://www.uni-bayreuth.de/pruefungsamt-bcg

### ITS Laptopsprechstunde {-}

Raum: 3.2.U1.164.3 (NW II)<br>
Tel.: 0921 / 55 - 3003 (ITS-Anlaufstelle)<br>
E-Mail: [laps@uni-bayreuth.de](mailto:laps@uni-bayreuth.de)<br>
Web: https://laps.uni-bayreuth.de

### Fachschaft BCG {-}

Zu finden sind wir im Gang des NW I, ganz in der Nähe der Hörsäle H13, H14 und H15.

Tel.: 0921 / 55 - 2212<br>
E-Mail: [fs-bcg@uni-bayreuth.de](mailto:fs-bcg@uni-bayreuth.de)<br>
Web: https://www.fsbcg.uni-bayreuth.de<br>
Öffnungszeiten: Mo. - Fr. 12.00 - 14.00 Uhr (oder einfach mal klopfen ... 😇)