on:
  pull_request:
    types: [closed]
    branches:
      - main

name: "Delete Repository of closed PR"

env:
  PR_REPO_NAME: ${{ github.event.repository.name }}_${{ github.event.pull_request.node_id }}

jobs:
  delete_repository:
    name: "Delete PR Repository"
    runs-on: ubuntu-latest
    steps:
      - name: "Delete repository for temporary deployment"
        uses: f1lander/delete-repository-action@0cdc2d8b1f6362b063d946e028af636e7b8a7b64
        with:
          owner: "fsbcg-ubt"
          repo: ${{ env.PR_REPO_NAME }}
          token: ${{ secrets.ORG_ADMIN_TOKEN }}