on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

name: "GitHub Pages deployment for PRs"

env:
  PR_REPO_NAME: ${{ github.event.repository.name }}_${{ github.event.pull_request.node_id }}
  PR_COMMENT_TEXT_BEGIN: "Das Ergebnis des PRs kann unter "
  PR_COMMENT_TEXT_END: " eingesehen werden. 📖👀"

jobs:
  create_repository:
    name: "Create PR Repository"
    runs-on: ubuntu-latest
    steps:
      - name: "Create new repository for temporary deployment"
        uses: f1lander/create-repository-action@790b25d255717b5a81416a8390f3344396181805
        with:
          name: ${{ env.PR_REPO_NAME }}
          org: "fsbcg-ubt"
          access-token: ${{ secrets.ORG_ADMIN_TOKEN }}

  test:
    name: "PWA E2E Tests"
    uses: ./.github/workflows/test-pwa-e2e.yml

  inject_pwa:
    name: "Inject PWA Files"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: "Setup Node.js"
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '20.19.1'
          cache: 'npm'
          cache-dependency-path: 'pwa/package-lock.json'
      - name: "Download GitBook artifact"
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: _book_gitbook
          path: _book
      - name: "Install Node.js dependencies"
        run: npm ci
        working-directory: pwa
      - name: "Compile TypeScript"
        run: npm run build
        working-directory: pwa
      - name: "Generate Service Worker"
        run: npx workbox-cli@7.3.0 generateSW dist/workbox-config.js
        working-directory: pwa
        env:
          BASE_PATH: /${{ env.PR_REPO_NAME }}
      - name: "Inject PWA files into HTML"
        run: node pwa/dist/inject-html.js
        env:
          BASE_PATH: /${{ env.PR_REPO_NAME }}
      - name: "Upload PWA-enabled artifact"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: _book_pwa
          path: _book/

  deploy_gitbook:
    needs: [create_repository, inject_pwa, test]
    name: "Deploy GitBook to PR Repository"
    runs-on: ubuntu-latest
    environment:
      name: pull-request-staging
      url: https://fsbcg-ubt.github.io/${{ env.PR_REPO_NAME }}/
    steps:
      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: "Set GitHub Actions as Commit Author"
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: "Checkout PR Repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: fsbcg-ubt/${{ env.PR_REPO_NAME }}
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
      - name: "Download artifact"
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: _book_pwa
      - name: "Push files to target"
        run: |
          touch .nojekyll
          git add .
          git commit -m $GITHUB_SHA
          git branch -M gh-pages
          git push -u origin gh-pages --force

  create_deployment_comment:
    needs: deploy_gitbook
    name: "Create comment with GH Pages URL"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        with:
          github-token: ${{ secrets.ORG_ADMIN_TOKEN }}
          script: |
            const commentBody = "${{ env.PR_COMMENT_TEXT_BEGIN }}https://fsbcg-ubt.github.io/${{ env.PR_REPO_NAME }}/${{ env.PR_COMMENT_TEXT_END }}"

            let commentFound = false
            await github.paginate(github.rest.issues.listComments, {
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
            })
            .then((comments) => {
              for (const comment of comments) {
                if (comment.body.includes("https://fsbcg-ubt.github.io/${{ env.PR_REPO_NAME }}")) {
                  commentFound = true
                }
              }
            })

            if (true == commentFound) {
              return
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })