on:
  release:
    types: [published]

name: "Release as GitBook (with PWA)"

jobs:
  build_gitbook:
    name: "Render GitBook"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fsbcg-ubt/docker-bookdown:0.3.7@sha256:3e45bec722a0b48560338f516ba2737b2b07bddf38a81aade9ff2b207e1822bc
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: "Render book as GitBook"
        run: Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
      - name: "Upload artifact"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: _book_gitbook
          path: _book/

  inject_pwa:
    name: "Inject PWA Files"
    runs-on: ubuntu-latest
    needs: build_gitbook
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: "Setup Node.js"
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '20.11.0'
          cache: 'npm'
          cache-dependency-path: 'pwa/package-lock.json'
      - name: "Download GitBook artifact"
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: _book_gitbook
          path: _book
      - name: "Install Node.js dependencies"
        run: npm ci
        working-directory: pwa
      - name: "Compile TypeScript"
        run: npm run build
        working-directory: pwa
      - name: "Generate Service Worker"
        run: npx workbox-cli@7.3.0 generateSW dist/workbox-config.js
        working-directory: pwa
        env:
          BASE_PATH: /erstizeitung
      - name: "Inject PWA files into HTML"
        run: node pwa/dist/inject-html.js
        env:
          BASE_PATH: /erstizeitung
      - name: "Upload PWA-enabled artifact"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: _book_pwa
          path: _book/

  publish_gitbook:
      name: "Publish on GitHub Pages"
      runs-on: ubuntu-latest
      needs: inject_pwa
      steps:
        - name: "Checkout Repository"
          uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        - name: "Download artifact"
          uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
          with:
            name: _book_pwa
            path: _book
        - name: "Publish to GitHub Pages"
          uses: Cecilapp/GitHub-Pages-deploy@e1d24a95b0050d8d97ce8647409a3b0d8d01ebeb # 3.3.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            email: fs-bcg@uni-bayreuth.de
            build_dir: _book/

#  build_pdf:
#    name: Render book as PDF
#    runs-on: macOS-latest
#    steps:
#      - name: "Checkout Repository"
#        uses: actions/checkout@v3
#      - name: "Install R"
#        uses: r-lib/actions/setup-r@v2
#      - name: "Install Pandoc"
#        uses: r-lib/actions/setup-pandoc@v2
#      - name: "Install TinyText"
#        uses: r-lib/actions/setup-tinytex@v2
#        env:
#          # install full prebuilt version
#          TINYTEX_INSTALLER: TinyTeX
#      - name: "Install R dependencies (and cache)"
#        uses: r-lib/actions/setup-r-dependencies@v2
#        with:
#          cache-version: 2
#          needs: |
#            rmarkdown
#            bookdown
#            tinytex
#      - name: "Render book as PDF"
#        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'
#      - name: "Upload artifact"
#        uses: actions/upload-artifact@v3
#        with:
#          name: _book_pdf
#          path: _book/