on:
  release:
    types: [published]

name: "Release as GitBook & PDF"

jobs:
  build_gitbook:
    name: "Render GitBook"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: "Render book as GitBook"
        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3.0.0
        with:
          image: fsbcgubt/docker-bookdown@sha256:958170419607ab75d841f4bb2049d8b3a39603af7a0a3af4e112aae0dbbb2884
          options: --mount src=${{ github.workspace }},target=/book,type=bind
          run: Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
      - name: "Upload artifact"
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: _book_gitbook
          path: _book/

  publish_gitbook:
      name: "Publish on GitHub Pages"
      runs-on: ubuntu-latest
      needs: build_gitbook
      steps:
        - name: "Checkout Repository"
          uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        - name: "Download artifact"
          uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v3.0.0
          with:
            name: _book_gitbook
            path: _book
        - name: "Publish to GitHub Pages"
          uses: Cecilapp/GitHub-Pages-deploy@64837616f5938346d4be701112e6941195bfd54a # v3.2.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            email: fs-bcg@uni-bayreuth.de
            build_dir: _book/

#  build_pdf:
#    name: Render book as PDF
#    runs-on: macOS-latest
#    steps:
#      - name: "Checkout Repository"
#        uses: actions/checkout@v3
#      - name: "Install R"
#        uses: r-lib/actions/setup-r@v2
#      - name: "Install Pandoc"
#        uses: r-lib/actions/setup-pandoc@v2
#      - name: "Install TinyText"
#        uses: r-lib/actions/setup-tinytex@v2
#        env:
#          # install full prebuilt version
#          TINYTEX_INSTALLER: TinyTeX
#      - name: "Install R dependencies (and cache)"
#        uses: r-lib/actions/setup-r-dependencies@v2
#        with:
#          cache-version: 2
#          needs: |
#            rmarkdown
#            bookdown
#            tinytex
#      - name: "Render book as PDF"
#        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'
#      - name: "Upload artifact"
#        uses: actions/upload-artifact@v3
#        with:
#          name: _book_pdf
#          path: _book/