on:
  release:
    types: [published]

name: "Release as GitBook & PDF"

jobs:
  build_gitbook:
    name: "Render GitBook"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: "Render book as GitBook"
        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3.0.0
        with:
          image: ghcr.io/fsbcg-ubt/docker-bookdown@sha256:3e45bec722a0b48560338f516ba2737b2b07bddf38a81aade9ff2b207e1822bc
          options: --mount src=${{ github.workspace }},target=/book,type=bind
          run: Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
      - name: "Upload artifact"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: _book_gitbook
          path: _book/

  publish_gitbook:
      name: "Publish on GitHub Pages"
      runs-on: ubuntu-latest
      needs: build_gitbook
      steps:
        - name: "Checkout Repository"
          uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        - name: "Download artifact"
          uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
          with:
            name: _book_gitbook
            path: _book
        - name: "Publish to GitHub Pages"
          uses: Cecilapp/GitHub-Pages-deploy@e1d24a95b0050d8d97ce8647409a3b0d8d01ebeb # 3.3.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            email: fs-bcg@uni-bayreuth.de
            build_dir: _book/

#  build_pdf:
#    name: Render book as PDF
#    runs-on: macOS-latest
#    steps:
#      - name: "Checkout Repository"
#        uses: actions/checkout@v3
#      - name: "Install R"
#        uses: r-lib/actions/setup-r@v2
#      - name: "Install Pandoc"
#        uses: r-lib/actions/setup-pandoc@v2
#      - name: "Install TinyText"
#        uses: r-lib/actions/setup-tinytex@v2
#        env:
#          # install full prebuilt version
#          TINYTEX_INSTALLER: TinyTeX
#      - name: "Install R dependencies (and cache)"
#        uses: r-lib/actions/setup-r-dependencies@v2
#        with:
#          cache-version: 2
#          needs: |
#            rmarkdown
#            bookdown
#            tinytex
#      - name: "Render book as PDF"
#        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'
#      - name: "Upload artifact"
#        uses: actions/upload-artifact@v3
#        with:
#          name: _book_pdf
#          path: _book/